### ISSUE TITLE
Setting CallbackFields in payment breaks the payment page

### ISSUE THREAD

**Issue by moeHaydar** [tmconsulting/uniteller-php-sdk#2]
A very simple example: 
```$builder
        ->setOrderIdp($payID)
        ->setSubtotalP($payment->amount)
        ->setCustomerIdp($customerID)
        ->setCallbackFields(array('BilNumber'))
        ->setUrlReturnOk(self::successPage())
        ->setUrlReturnNo(self::failPage());
```

Uniteller displays an error in payment page.

**Comment by roquie** [comment]
Try to wrap `self::successPage()` and `self::failPage()` using `urldecode` function.
Debug - Uniteller may show error in page source code:

![screen shot 2017-05-03 at 13 10 38](https://cloud.githubusercontent.com/assets/3214290/25656494/f40b3e66-3001-11e7-93dd-46aa9dcf5abe.png)

**Comment by moeHaydar** [comment]
Error I get when I add:```->setCallbackFields(array('BilNumber'))```
Error:
`MERCHANT ERROR: CallbackFormat is not valid`

From documentation:
![image](https://cloud.githubusercontent.com/assets/3309256/26029406/8533de7c-3834-11e7-991a-27a80403dda5.png)



Do you have any clue why this is failing ?

**Comment by roquie** [comment]
Try to use `BillNumber` parameter. Works?

**Comment by moeHaydar** [comment]
Just for reference for others.

The problem was that CallbackFields are not supported in the type of request I am doing.
I found documentation misleading (or i might have skipped a page)

**Comment by roquie** [comment]
Thanks for your answer, it will be userful for others 👍

**Comment by roquie** [comment]
By the way, parameter `BilNumber` incorrectly specified in the doc. It should be `BillNumber` (2 of l letter). I thought maybe problem was linked with him.
